language: swift
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
before_script:
- export LANG=en_US.UTF-8
rvm: 2.1.2
script:
- set -o pipefail && xcodebuild test -workspace Example/SVGPlayButton.xcworkspace -scheme SVGPlayButton-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
sudo: false
